# Generated by Django 4.0.3 on 2022-04-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0003_alter_funding_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
