# Generated by Django 4.0.3 on 2022-04-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0004_alter_funding_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funding',
            old_name='curr_num',
            new_name='total_num',
        ),
        migrations.AlterField(
            model_name='funding',
            name='dday',
            field=models.DateField(blank=True, verbose_name='D-Day(mm/dd/yyyy)'),
        ),
    ]
