# Generated by Django 4.0.3 on 2022-04-14 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0005_rename_curr_num_funding_total_num_alter_funding_dday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='invest',
        ),
    ]
