# Generated by Django 4.0.3 on 2022-04-14 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0006_remove_participant_invest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funding',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='people_total',
        ),
    ]
